"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 1500

scan_timeout = 10

[cmd_duration]
min_time = 500

[aws]
symbol = "ï”¬ "
style = "bold green"
format = 'on [$symbol($profile )(\($region\) )(\[$duration\])]($style)'

[azure]
disabled = false
format = "on [$symbol($subscription)]($style) "
symbol = "ï´ƒ "
style = "blue bold"

[battery]
full_symbol = "ï•¸ "
charging_symbol = "ï–ƒ "
discharging_symbol = "ï•¼ "
unknown_symbol = "ï–‚ "

[[battery.display]]
threshold = 30
style = "bold red"

[dart]
symbol = "î˜ "
format = "via [$version](bold green) "

[directory]
truncation_length = 2
read_only = " ï ½"

[directory.substitutions]
"Documents" = "Documents ïœ˜"
"Downloads" = "Downloads ï€™"
"Music" = "Music ï€"
"Pictures" = "Pictures ï€¾"

[docker_context]
symbol = "ïŒˆ "
style = "bold blue"
only_with_files = true
disabled = false

[git_branch]
symbol = "ï˜ "

[git_commit]
commit_hash_length = 8

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[golang]
symbol = "î˜§ "

[helm]
format = 'via [$symbol]($style)'

[java]
symbol = "î‰– "
style = "bold green"

[jobs]
symbol = "ğŸƒâ€â™‚ï¸ "
threshold = 1

[kubernetes]
symbol = 'ï´± '
style = "bold blue"
format = 'on [$symbol$context( \($namespace\))]($style) in '
disabled = false

[lua]
symbol = 'î˜  '

[memory_usage]
symbol = "ï¡š "

[package]
display_private = true

[php]
symbol = "î˜ˆ "

[scala]
style = "bold red"
symbol = "îœ· "

[python]
style = "bold yellow"
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "î¨ "

[username]
style_user = "white bold"
style_root = "black bold"
format = "îœ‘ [$user]($style) "
disabled = false
show_always = true
